const MenuResponseData = [
    {
        id: 0,
        title: 'Rice',
        data: [
            'Fried Rice',
            'Steamed Jasmine Rice',
            'Brown Rice Pilaf',
            'Coconut Basmati Rice',
            'Wild Mushroom Risotto',
            'Spanish Paella',
            'Teriyaki Chicken Bowl',
            'Vegetable Biryani',
            'Lemon Herb Quinoa',
            'Saffron Infused Rice',
            'Mexican Cilantro Lime Rice',
            'Mushroom and Pea Risotto',
        ],
    },
    {
        id: 1,
        title: 'Salads',
        data: [
            'Caesar Salad',
            'Greek Salad',
            'Cobb Salad',
            'Caprese Salad',
            'Spinach and Strawberry Salad',
            'Mango Avocado Salad',
            'Asian Sesame Chicken Salad',
            'Quinoa and Black Bean Salad',
            'Waldorf Salad',
            'Kale and Cranberry Salad',
            'Watermelon and Feta Salad',
            'Mediterranean Tabbouleh Salad',
        ]
    },
    {
        id: 2,
        title: 'Pasta',
        data: [
            'Spaghetti Carbonara',
            'Penne Arrabbiata',
            'Fettuccine Alfredo',
            'Linguine with Clams',
            'Lasagna',
            'Ravioli with Pesto',
            'Shrimp Scampi Linguine',
            'Tortellini Primavera',
            'Mac and Cheese',
        ],
    },
    {
        id: 3,
        title: 'Desserts',
        data: [
            'Chocolate Cake',
            'Apple Pie',
            'Tiramisu',
            'Cheesecake',
            'Ice Cream Sundae',
            'Panna Cotta',
            'Key Lime Pie',
            'Creme Brulee',
            'Fruit Tart',
        ],
    },
    {
        id: 4,
        title: 'Seafood',
        data: [
            'Grilled Salmon',
            'Shrimp Scampi',
            'Fish Tacos',
            'Lobster Bisque',
            'Crab Cakes',
            'Clam Chowder',
            'Fish and Chips',
            'Sushi Rolls',
        ],
    },
    {
        id: 5,
        title: 'Burgers',
        data: [
            'Classic Cheeseburger',
            'Bacon Avocado Burger',
            'Mushroom Swiss Burger',
            'BBQ Chicken Burger',
            'Veggie Burger',
            'Spicy Black Bean Burger',
            'Turkey Burger',
        ],
    },
    {
        id: 6,
        title: 'Pizza',
        data: [
            'Margherita Pizza',
            'Pepperoni Pizza',
            'Vegetarian Pizza',
            'BBQ Chicken Pizza',
            'Hawaiian Pizza',
            'Supreme Pizza',
            'White Garlic Pizza',
        ],
    },
];

export default MenuResponseData;
